[project]
name = "monitoring-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "confluent-kafka>=2.13.0",
    "faker==22.0.0",
    "pg8000==1.30.5",
    "rav>=0.4.3",
    "streamlit>=1.42.0",
]
