apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: heartbeat-postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: heartbeat_db
    user: heartbeat_user
    secureJsonData:
      password: heartbeat_pass
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1500
    isDefault: true
    editable: true
